name: bridgecare
description: "Manejo y mantenimiento de puentes."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  persistent_bottom_nav_bar: any
  tutorial_coach_mark: ^1.2.13
  shared_preferences: ^2.5.2
  provider: ^6.1.2
  google_fonts: ^5.0.0
  image_picker: ^0.8.6+1
  http: ^1.3.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo_no_letters_1152.png"
  adaptive_icon_background: "#111d2c"  # Background color
  adaptive_icon_foreground: "assets/images/logo_no_letters_1152.png"

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#111d2c"
  image: assets/images/logo_no_letters_768.png
  icon_background_color: "#FFFFFF"
  android_12:
    color: "#111d2c"
    image: assets/images/logo_no_letters_768.png
    icon_background_color: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Light.ttf
  #         weight: 100
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 400
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 600
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
