name: bridgecare
description: "Manejo y mantenimiento de puentes."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.0
  flutter_image_compress: ^2.4.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  flutter_notification_channel: ^3.1.1
  flutter_pdfview: ^1.3.1
  google_fonts: ^5.0.0
  http: ^1.3.0
  image: ^4.5.4
  image_picker: ^1.1.2
  jwt_decoder: ^2.0.1
  lottie: ^3.3.1
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  persistent_bottom_nav_bar: any
  provider: ^6.1.5
  shared_preferences: ^2.5.2
  sqflite: ^2.4.2
  tutorial_coach_mark: ^1.2.13
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo_no_letters_1152.png"
  adaptive_icon_background: "#111d2c"  # Background color
  adaptive_icon_foreground: "assets/images/logo_no_letters_1152.png"

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#111d2c"
  image: assets/images/logo_no_letters_768.png
  icon_background_color: "#FFFFFF"
  android_12:
    color: "#111d2c"
    image: assets/images/logo_no_letters_768.png
    icon_background_color: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/puente.json
    - assets/pdf/
    - assets/data/
    - assets/fonts/

  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
        - asset: assets/fonts/JosefinSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/JosefinSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/JosefinSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/JosefinSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/JosefinSans-LightItalic.ttf
          style: italic

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Light.ttf
  #         weight: 100
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 400
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 600
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
